### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by XusBadia** [bacbos/bolt-menu-editor#19]
I apologize for the noob question, but is there a guide or similar on how to get started? I installed the extension and I see it in Extras in Bolt. But after I created a menu, how do I add it to a template?

Thanks!

**Comment by bacbos** [comment]
Hi Xus. This extension does nothing more than provide a visual interface to edit the menu.yml file.
Please see https://docs.bolt.cm/menus for an introduction to menus in bolt.

To insert the menu in your template, it's as easy as calling `{{ menu() }}` in your template.
