### ISSUE TITLE
Custom fields gone upon save

### ISSUE THREAD

**Issue by DennisSnijder** [bacbos/bolt-menu-editor#22]
in the YML file i made a custom field called 'logo'
after editing the menu with menu editor the 'logo' field was gone.

it would be nice if there was some kind of support for custom fields.

**Comment by bacbos** [comment]
I added a new tag 2.2.2 based on PR https://github.com/bacbos/bolt-menu-editor/pull/21
Is this working for you?

**Comment by DennisSnijder** [comment]
upon installing new 2.2.2 version i get this

![image](https://cloud.githubusercontent.com/assets/6953846/13122955/e3a5ec36-d5b9-11e5-9b54-1bd7f6d1ef1b.png)

**Comment by DennisSnijder** [comment]
@bacbos installing the extension manually works, also the custom fields works for me. thanks :)
