### ISSUE TITLE
Poor performance on large data sets

### ISSUE THREAD

**Issue by C4Grey** [bacbos/bolt-menu-editor#25]
Hi!
In cases if there are huge amounts of content per a few content types, Menu Editor loading time increasing dramatically(~30 seconds). I've found that this [line of code](https://github.com/bacbos/bolt-menu-editor/blob/959950a51063dab01249e79560fd55efb1263528/Extension.php#L327) looks like it loads all content of all content types...I don't know why menu editor should do this, but when I've removed this line the editor still works well and a loading time value become normal(~400ms).

**Comment by bacbos** [comment]
You're right, it should not be doing this.
Looking over it quickly, I'd say this is a relict from when the menu-editor was not using ajax-searching through content-types, so it loaded everything in advance to populate the static select-field.

Do you mind sending in a PR? :)

**Comment by C4Grey** [comment]
Done, awaits for approval

**Comment by bacbos** [comment]
Great, thanks a lot!
