### ISSUE TITLE
app.js:21 Uncaught TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by santi6291** [bacbos/bolt-menu-editor#29]
JavaScript error  `me.init();`, me is undefined

V 2.2.1 (upgraded to 2.2.4 and did nothing)

This is happening on my local environment but on my staging server its fine, found it very odd. I also tried uninstalling and re installing but the error keeps happening

**Comment by SahAssar** [comment]
@santi6291 When I've run into this it was because I had other JS loaded in the backend which interfered with requirejs that the menu editor uses. Do you have any custom extensions that add JS to the backend?
