### ISSUE TITLE
3.0 support

### ISSUE THREAD

**Issue by jnvsor** [bacbos/bolt-menu-editor#31]

**Comment by Largo** [comment]
https://github.com/Largo/bolt-menu-editor/tree/patch-2
Clone this to extensions/local

Directory paths should be like this
extensions/local/bacboslab/menueditor: config... src... templates etc.

**Comment by SahAssar** [comment]
I've been planning to take a shot at it since I'm basically done with translate for now... But I'd probably change a few things if that'd be okay with @bacbos, like for example replacing https://github.com/dbushell/Nestable which hasn't been supported/updated since Aug 2014.

**Comment by bacbos** [comment]
https://github.com/GawainLynch/bolt-extension-menu-editor/pull/1

**Comment by SahAssar** [comment]
I've got most of it up and running now, but it'll need some more UI love (Which I'll get to in the comming days). One thing I wanted to check with you guys about is the search/add item field... Currently i have it like this:

![image](https://cloud.githubusercontent.com/assets/5096632/17025499/6836ccec-4f5c-11e6-83a4-798a2d04cb06.png)

So basically one field searches everything, and shows excerpts, mini-thumbnails (if available), and is also used to create plain links. Any feedback? On the basic idea that is, I'm still fixing details with it and will work on making it more intuitive.

**Comment by GawainLynch** [comment]
:koala: says :+1:

**Comment by xiaohutai** [comment]
@SahAssar very nice! It's perhaps an idea to incorporate that with the Omnisearch in the back-end as well.
