### ISSUE TITLE
3.1 Version IE11 bug

### ISSUE THREAD

**Issue by Largo** [bacbos/bolt-menu-editor#33]
Apparently the item selection list doesn't show on IE11

**Comment by SahAssar** [comment]
Right, after some testing this seems to be a a bug in select2, probably select2/select2#4398.

@Largo Could you confirm that you see the same issue in bolt's omnisearch? Cause the 3.1 version of the menueditor uses bolt's version of select2, so if it indeed is the select2 issue we should see the same issue in the omnisearch (which is what I'm seeing in my testing).

**Comment by Largo** [comment]
ah, I'm actually still using bolt 3.0 if that makes any difference for
select2
I tried to upgrade to the bolt 3.1 branch but somehow they don't use that
new public folder separation anymore?
It's a pain to setup on shared hosting (upload 1m files again, htaccess,
_bolt.yml etc), but I managed to do it, so I was hesistant to go back, when
it wasn't clear if I have to redo it again.

I'll test later.

**Comment by SahAssar** [comment]
Ah, If it's a hassle for you to test don't do it. I'll just do some more testing on browserstack and then open an issue in bolt/bolt that there is a upstream issue in select2.

**Comment by SahAssar** [comment]
Opened an issue about this in bolt/bolt#5676.

**Comment by navelpluisje** [comment]
@Largo Is this one still valid? Or can it be deleted?

**Comment by SahAssar** [comment]
I tried a few different versions of select2, but all the recent ones (when this was brought up) were broken. That might have changed since then though, I haven't had time to check.

**Comment by SahAssar** [comment]
We've reverted this to select2 4.0.0 (that didn't bug out) in bolt core. It'll be in the next bolt release, so I'm closing this one, please reopen if bugs out then too.
