### ISSUE TITLE
Possible Missing Strings

### ISSUE THREAD

**Issue by eduardomart** [bacbos/bolt-menu-editor#35]
Currently this is what the backend looks like, in Bolt 3.1

![screen shot 2016-08-29 at 5 51 47 pm](https://cloud.githubusercontent.com/assets/1833020/18072266/99f0978a-6e11-11e6-8097-1d507401722f.png)

**Comment by bacbos** [comment]
What locale is configured in your bolt?

**Comment by eduardomart** [comment]
English, the default

**Comment by SahAssar** [comment]
@eduardomart Try clearing you bolt cache, it might just be that the translations were not loaded into the cache when the extension was installed.

**Comment by eduardomart** [comment]
Thanks @SahAssar, I guess that was it.

**Comment by SahAssar** [comment]
@eduardomart I opened an issue in bolt/bolt to get this fixed, hopefully we'll get if fixed soon.
