### ISSUE TITLE
Putting a link to the menu editor in the sidebar

### ISSUE THREAD

**Issue by bajesus** [bacbos/bolt-menu-editor#38]
In the old menu editor config there was a permissions setting that would allow you to set who would see the menu editor. 

Like this:
`permissions: [ admin, developer, chief-editor ]`

That doesn't seem to work now.  Is there a way to do this in the new editor?  If not I think it is an important feature to have.  I would prefer not to have to make every user who can edit the menu an admin.

**Comment by bacbos** [comment]
This feature is re-added in release 3.1.3 thanks to @navelpluisje
