### ISSUE TITLE
Feature request: warning against closing unsaved changes

### ISSUE THREAD

**Issue by evertalbers** [bacbos/bolt-menu-editor#40]
In the normal Bolt editor, when you are leaving a page before saving your latest changes, you get a warning that there are still unsaved changes. (shown below in Dutch)

Would it be possible to do the same in the MenuEditor? Would be handy since you've already done a couple of actions to change stuff, and see the whole menu in front of you, which makes you think you're done. Not everybody will realise that they will have to hit the **Save Menu** (a.k.a. **Spara Menyerna**) button before it is actually saved.

![schermafbeelding 2016-09-19 om 21 47 41](https://cloud.githubusercontent.com/assets/3974120/18646811/8ab7413a-7eb3-11e6-9e0d-3369677a4d9e.png)

**Comment by SahAssar** [comment]
This looks very possible and very useful... I'll see if I can knock something out soon :)

**Comment by SahAssar** [comment]
Closing, if anyone is actively working on this let me know and we'll work on merging.
