### ISSUE TITLE
Custom fields are empty

### ISSUE THREAD

**Issue by frozenshadow** [bacbos/bolt-menu-editor#41]
When saving a menu item with custom fields, the page refreshes but the custom fields are empty.
They are however successfully saved to the menu.yml file.

Tested on Bolt 3.1.4 with menu editor 3.1.3.

**Comment by SahAssar** [comment]
Yeah, probably my fault... Lemme check it out and I'll return with a fix.

**Comment by SahAssar** [comment]
Fix PR'ed now.
