### ISSUE TITLE
Translation files not being added to the translator - twig is outputting the keys

### ISSUE THREAD

**Issue by graham73may** [bacbos/bolt-menu-editor#42]
New Bolt install, all I've done so far is setup some taxonomies and contenttypes. I've installed relationlist and this plugin. When I go to use the menu editor I'm seeing all the dynamic values output (screenshot attached). 

![image](https://cloud.githubusercontent.com/assets/6642498/19572004/600b1b16-96f8-11e6-9d70-e2b46573a47c.png)

Am I doing something wrong here? I've installed the plugin and gone to use it. 

Thank you!

Bolt 3.1

**Comment by graham73may** [comment]
I found the thread Possible missing strings #35 after posting this. 

I've cleared my Bolt cache as suggested but still have missing strings throughout like my original screenshot.

**Comment by graham73may** [comment]
Translations aren't being added to the en catalogue even after clearing the cache. 

Possible cause: https://github.com/bolt/bolt/issues/5921

**Comment by graham73may** [comment]
Slack Discussion: 
> It doesn’t look like that extension is adding the translation files to the translator

**Comment by SahAssar** [comment]
This is probably the same as #35, which is caused by bolt/bolt#5727, try clearing the cache and see if that fixes it.

**Comment by graham73may** [comment]
Submitted a new issue on the bolt repo. 

Turns out it is because I'm using a Windows file system. (And that's happened because of the lack of macbook updates in recent years, so I think the origin of this issue is Apple right?)
https://github.com/bolt/bolt/issues/5931
