### ISSUE TITLE
Add default (english) values to translation strings to prevent 'unreadable' string

### ISSUE THREAD

**Issue by navelpluisje** [bacbos/bolt-menu-editor#50]
By adding the english translation as a default value to the translations, the dot-seperated keys will not appear when a translation fails like in https://github.com/bacbos/bolt-menu-editor/issues/48.

**Comment by SahAssar** [comment]
I'm not against it per se, but isn't this just covering up the real issue?

**Comment by navelpluisje** [comment]
True, but for the time being it will help people see a proper and understandable text after installation. See it more as a service until it is solved in Bolt;-)

**Comment by SahAssar** [comment]
Righto, sounds good

**Comment by navelpluisje** [comment]
Shall we do this one before releasing a new version. Just to take some annoyance away about the translation?

**Comment by SahAssar** [comment]
Sounds good

**Comment by SahAssar** [comment]
Fixed in #51 and added to the latest tagged release.
