### ISSUE TITLE
[Bolt 3.3] Change Mount Url

### ISSUE THREAD

**Issue by rossriley** [bacbos/bolt-menu-editor#54]
Just a preemptive issue.

With Bolt 3.3 the menu has been changed from `/extend` to `/extensions` so a 3.3 compatible release will need this line updating: https://github.com/bacbos/bolt-menu-editor/blob/master/src/MenueditorExtension.php#L44

**Comment by bacbos** [comment]
Thanks for the heads up. Is there an easy way to fetch the current release tag from within an extension?

**Comment by navelpluisje** [comment]
@bacbos Found how to determine the version. Will create a PR tonight

**Comment by bacbos** [comment]
Awesome, thank you @navelpluisje

**Comment by SahAssar** [comment]
Fixed in #55
