### ISSUE TITLE
not linking to assets properly

### ISSUE THREAD

**Issue by ChangePlaces** [bacbos/bolt-menu-editor#58]
I've just installed bolt and menueditor, so this may be somewhat my fault, but when viewing the menu editor, the necessary js files aren't being pulled properly. I'm seeing 404's to bacboslab/menueditor/jquery.... instead of pulling them from the web directory.

Have I not installed it properly (I used the builtin installer) or is this really an issue?

**Comment by navelpluisje** [comment]
@ChangePlaces What version of Bolt did you install and what version of the menueditor?

**Comment by SahAssar** [comment]
Closing since it has been over a month without reply. @ChangePlaces Please reopen when you have the info!

**Comment by Matthewbeck75** [comment]
I'm getting this issue too, version 3.2.10 of Bolt and 3.2.1 of Menu Editor.
The extension is looking in /extensions/vendor/bacboslab/menueditor/ for css and JS files, but my web root is /public/ .

**Comment by SahAssar** [comment]
@Matthewbeck75 Yeah, bolt needs to sync the assets when the extension is installed, so it needs write permissions to the public/extensions folder.
