### ISSUE TITLE
Uncaught Exception: SyntaxErrorException with Repeaters in a CT

### ISSUE THREAD

**Issue by melcarthus** [bacbos/bolt-menu-editor#61]
# Uncaught Exception: SyntaxErrorException

When I have repeater setup inside a Contenttype I get an 500 server error when I use the search inside the plugin.

When I remove the repeat and do a search in the plugin again, everything works fine.

`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ) GROUP BY bolt_sections.id' at line 1`

**Comment by SahAssar** [comment]
Hey @melcarthus!

Which bolt version and which menueditor version is this on? Also this is on MySQL, right?

**Comment by SahAssar** [comment]
I'm pretty sure this is fixed in bolt-core since this was opened. let me know otherwise.
