### ISSUE TITLE
[RFC] Add feedback after adding an item

### ISSUE THREAD

**Issue by anketwokings** [bacbos/bolt-menu-editor#74]
This happens especially when you have larger menus that are larger then your viewport.
## How to reproduce
- in existing menu, add an item ( box on right)
- Add a label for the new item
- Start typing name of page , e.g.`/page/this-is-my-page`
- Select a page that shows in the pulldown

**Result**: link/path field is cleared and nothing _seems_ to happen
**What does happen**: On selecting the page, the new item is placed on the bottom of the menu. This might be out of your viewport. Hence the feeling that 'nothing happens and it's broken'

## Possible solutions
Option 1: 
- Have a `Add item` button that you have to click actively after selecting the page. (This way you actually have a last check, when both fields are filled out)
- Directly scroll to new item after click on `add item`

Option 2:
- A dialog that says: `Succes! We added Item blabla and put it on bottom of your menu`

### Background
I First wanted to file a bug for 'it's broken, nothing happens when I add a new item' and then I discovered 10 new items with the same label somewhere on the bottom of my menu..

**Comment by SahAssar** [comment]
Sounds good to me, do you want to PR that? it's probably just something like adding a line with `showFlash('Menuitem added!')` here: https://github.com/bacbos/bolt-menu-editor/blob/master/web/menueditor.js#L222

**Comment by anketwokings** [comment]
Yes, I was thinking of digging into it and doing exactly that. Thnx for pointing out where!
