### ISSUE TITLE
Input field to add item is buggy in IE11

### ISSUE THREAD

**Issue by anketwokings** [bacbos/bolt-menu-editor#76]
Hi all!

Sorry to add another buggy thing to the issues. :)

## How to reproduce
* Open an IE11 somewhere on your computer
* try to add a menu item: first label (no problem), then path/link 
* Problem: The input field for path/link only shows 1 typed character and does not display any suggestions

![menueditor-ie11-buggybugy](https://user-images.githubusercontent.com/5583671/36736291-84cf8480-1bd8-11e8-86d4-dc92b64a6b60.png)

### What happens?
The inline style of the input field is set to `` style="width: .75em;"`` . And not updated when typing.

### What should happen?
In chrome and FF, the inline style is updated with every typed character. 

### But why?
It seems to me like a [select2](https://github.com/select2/select2) problem, but looking at their open issues I could not find a similar issue.

------
Using menu editor 3.2.4
Did only test on IE11 since client is a) Noob and b) is completely lost that this doesn't work .. ;)

**Comment by anketwokings** [comment]
**Addition** 

This seems to be a select2 issue, because the _Omnisearch_ in Bolt is also broken in IE11.
There it's less obvious, because the width is set correctly, but there are no suggestions shown at all.

**Comment by SahAssar** [comment]
Yeah, see bolt/bolt/issues/5676 and #33 for some details... not sure how to fix this without rewriting it to not use select2 or getting a fix and release in upstream.

**Comment by SahAssar** [comment]
I'm going to close this one, since it seems unreasonable to solve it here. The menueditor depends on bolt, which depends on select2, which has had exactly 1 proper commit since Nov 22, 2017 (and even that was a translation-only commit).

I'm going to update the readme to say that we do not support IE period, and PR the same for bolt.

**Comment by SahAssar** [comment]
bolt/bolt#7432
