### ISSUE TITLE
Does this extension work out of the box if bolt is installed via composer?

### ISSUE THREAD

**Issue by use** [bacbos/bolt-menu-editor#8]
When I install Bolt with composer, then install this extension, I see some resources are resulting in 404:

 * /extensions/vendor/bacboslab/menueditor/assets/bower_components/requirejs/require.js
 * /extensions/vendor/bacboslab/menueditor/assets/bolt-menu-editor/menueditor.css
 * /extensions/vendor/bacboslab/menueditor/assets/app.js

Which causes the menu editor's UI to not function.

Comparing [this extension's composer.json](https://github.com/bacbos/bolt-menu-editor/blob/master/composer.json) to the [composer.json of a sample extension](https://github.com/GawainLynch/bolt-extension-clippy/blob/master/composer.json), I don't see an extra/bolt-assets entry - is that why bolt doesn't know to copy these assets to my webroot's /extensions folder?

**Comment by bacbos** [comment]
Hi Will - there have already been other bugs with the menu editor in the past that turned up when bolt was installed with composer (-> https://github.com/bolt/composer-install), so it's likely that this bug is caused somewhere similar, but I'll look into this in more detail and get back to you.

**Comment by bacbos** [comment]
@use , I've just pushed an update (2.0.4), the installation is working for me now for both installation methods (composer-style and git-clone style), try it out.

**Comment by use** [comment]
@bacbos Hey that works perfectly now.  Thank you.
